services:
  ## HubCMD UI
  hubcmd-ui:
    container_name: hubcmd-ui
    image: dqzboy/hubcmd-ui:latest
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      # 配置目录
      - ./data/config:/app/data
      # 文档目录
      - ./data/docs:/app/documentation
      # 用户数据,需提前在宿主机上创建并把项目users.json内容放入
      - ./data/user/users.json:/app/users.json
    ports:
      - 30080:3000
