services:
  ## HubCMD UI
  hubcmd-ui:
    container_name: hubcmd-ui
    image: dqzboy/hubcmd-ui:latest
    build:
      context: ..
      dockerfile: ./Dockerfile
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      # 配置目录(menu.json 和 monitor.json)
      - ./data/config:/app/config
      # 文档目录(Markdown 文档)
      - ./data/docs:/app/documentation
      # menu.json 和 monitor.json 的目录
      - ./data/data/:/app/data
      
    ports:
      - 30080:3000
